@host = http://localhost:5000/api/v1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJuYW1lIjoibVpvcnJvIiwiaWF0IjoxNjUyNzY3MTY2LCJleHAiOjE2NTUzNTkxNjZ9.wgS-hiyd05o2ch94TwuLb_-gb0C3-QuFwCKcrHoZytU

###
POST {{host}}/login HTTP/1.1
content-type: application/json
# Authorization: Bearer {{token}}
# lazy_chat_token: 2c6b7c0ae95845eab685dfa945647da7

{
    "username": "mZorro",
    "password": "password"
}

###
GET {{host}}/dashboard HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
# lazy_chat_token: 2c6b7c0ae95845eab685dfa945647da7

{
    
}